### ISSUE TITLE
Address Sanitizer

### ISSUE THREAD

**Issue by tiennou** [quicksilver/Quicksilver#2176]
Go to Scheme > Diagnostics > Enable Address Sanitizer, Run. Enjoy :heart_eyes: !

**Comment by tiennou** [comment]
That's *2 complete seconds after startup*.

```
=================================================================
==7734==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x700000115664 at pc 0x00010013f9cd bp 0x7000001155b0 sp 0x700000114d68
READ of size 7 at 0x700000115664 thread T3
    #0 0x10013f9cc in wrap_strlen (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x3d9cc)
    #1 0x7fff89ff1bae in +[NSString stringWithCString:encoding:] (/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation+0x3cbae)
    #2 0x100eb02eb in -[NSString(Hex) decodedHexString] NSString_BLTRExtensions.m:254
    #3 0x100eaf027 in -[NSString(Hex) decodedPasteboardType] NSString_BLTRExtensions.m:241
    #4 0x1010a22e9 in -[QSObject(Pasteboard) addContentsOfPasteboard:types:] QSObject_Pasteboard.m:99
    #5 0x1010a2ced in -[QSObject(Pasteboard) initWithPasteboard:types:] QSObject_Pasteboard.m:118
    #6 0x1010a1682 in -[QSObject(Pasteboard) initWithPasteboard:] QSObject_Pasteboard.m:80
    #7 0x1010a000d in +[QSObject(Pasteboard) objectWithPasteboard:] QSObject_Pasteboard.m:50
    #8 0x108e886e7 in 0x0000000108e886e7 (/Users/tiennou/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSClipboardPlugIn.142.qsplugin/Contents/MacOS/Clipboard Plugin+0x56e7)
    #9 0x100144903 in __wrap_dispatch_async_block_invoke (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x42903)
    #10 0x101335fa3 in _dispatch_call_block_and_release (/usr/lib/system/introspection/libdispatch.dylib+0xefa3)
    #11 0x101328bf8 in _dispatch_client_callout (/usr/lib/system/introspection/libdispatch.dylib+0x1bf8)
    #12 0x10132e045 in _dispatch_queue_drain (/usr/lib/system/introspection/libdispatch.dylib+0x7045)
    #13 0x101335d57 in _dispatch_queue_invoke (/usr/lib/system/introspection/libdispatch.dylib+0xed57)
    #14 0x101328bf8 in _dispatch_client_callout (/usr/lib/system/introspection/libdispatch.dylib+0x1bf8)
    #15 0x10132d38a in _dispatch_root_queue_drain (/usr/lib/system/introspection/libdispatch.dylib+0x638a)
    #16 0x10132c7d8 in _dispatch_worker_thread3 (/usr/lib/system/introspection/libdispatch.dylib+0x57d8)
    #17 0x10138b457 in _pthread_wqthread (/usr/lib/system/introspection/libsystem_pthread.dylib+0x3457)
    #18 0x101388fac in start_wqthread (/usr/lib/system/introspection/libsystem_pthread.dylib+0xfac)

Address 0x700000115664 is located in stack of thread T3 at offset 100 in frame
    #0 0x100eafa8f in -[NSString(Hex) decodedHexString] NSString_BLTRExtensions.m:248

  This frame has 5 object(s):
    [32, 48) ''
    [64, 80) 'r.i'
    [96, 100) 's' <== Memory access at offset 100 overflows this variable
    [112, 116) 'x'
    [128, 144) ''
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T3 created by T0 here:
    <empty stack>

SUMMARY: AddressSanitizer: stack-buffer-overflow ??:0 wrap_strlen
Shadow bytes around the buggy address:
  0x1e0000022a70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022a90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022aa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022ab0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1e0000022ac0: f1 f1 f1 f1 00 00 f2 f2 00 00 f2 f2[04]f2 04 f2
  0x1e0000022ad0: 00 00 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0000022b10: f1 f1 f1 f1 00 f3 f3 f3 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7734==ABORTING
```
